version: 2.1
jobs:
  build:
    working_directory: ~/V2DSprite
    docker:
      - image: circleci/openjdk:11.0.6-jdk-stretch
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install xvfb -y
      - checkout
      - restore_cache:
          key: V2DSprite-{{ checksum "pom.xml" }}
      - run: xvfb-run -a mvn clean install -U
      - save_cache:
          paths:
            - ~/.m2
          key: V2DSprite-{{ checksum "pom.xml" }}
      - run: xvfb-run -a mvn test
      - store_test_results:
          path: target/surefire-reports